sudo: required

arch:
  packages:
    - namcap 
  script:
    - namcap PKGBUILD      
    - makepkg
    - namcap coursier-*  
    - pacman -Qip coursier-*
    - pacman -Qlp coursier-*
  

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
